services:
    ipc.security.doctine_user_provider:
        class:     IPC\SecurityBundle\Provider\DoctrineUserProvider
        arguments: [ "@doctrine", IPC\SecurityBundle\Entity\User ]

    ipc.security.form.type.login:
        class: IPC\SecurityBundle\Form\Type\LoginType
        tags:
            - { name: form.type, alias: login }
