login:
    path:     /login
    defaults: { _controller: IPCSecurityBundle:Security:login }
login_check:
    path:     /login_check
logout:
    path:     /logout

credentials_expired:
    path:     /credentials_expired
    defaults: { _controller: IPCSecurityBundle:Security:credentialsExpired }

profiler_enable:
    path:     /profiler/enable
    defaults: { _controller: IPCSecurityBundle:Profiler:enable }
profiler_disable:
    path:     /profiler/disable
    defaults: { _controller: IPCSecurityBundle:Profiler:disable }
profiler_status:
    path:     /profiler/status
    defaults: { _controller: IPCSecurityBundle:Profiler:status }
