services:
    ipc.security.doctine_user_provider:
        class:     IPC\SecurityBundle\Provider\DoctrineUserProvider
        arguments: [ "@doctrine", "%ipc_security.doctrine_user_provider.entity_class%", "%ipc_security.doctrine_user_provider.username_properties%" ]

    ipc.security.service.security_token:
        class: IPC\SecurityBundle\Service\SecurityToken
        arguments: [ "@security.token_storage", "@session" ]

    ipc.security.form.type.login:
        class: IPC\SecurityBundle\Form\Type\LoginType
        tags:
            - { name: form.type, alias: login }

    ipc.security.form.type.change_password:
        class: IPC\SecurityBundle\Form\Type\ChangePasswordType
        tags:
            - { name: form.type, alias: change_password }
