IPC\SecurityBundle\Form\Model\ChangePassword:
  properties:
    current:
      - IPC\ValidatorBundle\Validator\Constraints\Chain:
          constraints:
            - NotBlank:
                message: form.model.change_password.current.not_blank
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                message: form.model.change_password.current.user_password
          groups: [ require_current ]
    new:
      - NotBlank:
          message: form.model.change_password.new.not_blank

  constraints:
    - IPC\ValidatorBundle\Validator\Constraints\EqualProperties:
        message: form.model.change_password.constraints.equal_properties
        properties: ['new', 'current']
        invert: true
        groups: [ require_current ]