IPC\SecurityBundle\Form\Model\ChangePassword:
  properties:
    current:
      - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
          message: form.model.change_password.current.UserPassword
          groups: [ require_current ]
    new:
      - NotBlank:
          message: form.model.change_password.new.NotBlank

  constraints:
    - IPC\ValidatorBundle\Validator\Constraints\EqualProperties:
        message: form.model.change_password.constraints.equal_properties
        properties: ['new', 'current']
        invert: true